import { supportedEncoderValueType } from "./decode_property";

export const ENCODE_VALUE_IDS: { [index in supportedEncoderValueType]: number } = {
	string: 0,
	boolean: 1,
	number: 2,
	CFrame: 3,
	EnumItem: 4,
	Vector3: 5,
	Instance: 6,
	Color3: 7,
	UDim2: 8,
	Vector2: 9,
};

// put property names here to optimize them
export const INDEX_IDS: { [index: string]: number | undefined } = {
	TextureID: 0,
	MeshId: 1,
	Scale: 2,
	Transparency: 3,
	Reflectance: 4,
	Material: 5,
	Anchored: 6,
	CFrame: 7,
	Size: 8,
	Color3: 9,
	TextColor3: 10,
	Text: 11,
	TextSize: 12,
	TextWrapped: 13,
	Color: 14,
	CollisionGroup: 15,
	CanQuery: 16,
	CanTouch: 17,
	CanCollide: 18,
	Locked: 19,
	Position: 20,
	Brightness: 21,
	AnchorPoint: 22,
	BackgroundColor3: 23,
	BackgroundTransparency: 24,
	Range: 25,
	Name: 26,
	TextureId: 27,
	OffsetStudsU: 29,
	OffsetStudsV: 30,
	StudsPerTileU: 31,
	StudsPerTileV: 32,
	Texture: 33,
	ZIndex: 35,
};
